services:
  postgres:
    image: postgres:15
    container_name: universal-marketplace-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: universal-marketplace-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: localpassword
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_HOUR: ${JWT_EXPIRATION_HOUR}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}