spring.application.name=universal-marketplace-be
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
#usunąć przy deployu |
#                   \ /
#                    v
spring.jpa.hibernate.ddl-auto=create-drop

jwt.expiration.hour=24
jwt.secret=${jwt-secret:polkmiujhbtrfdxsqsdxcwedfgvbthjm}